GET http://localhost:3000/todoshhh

###

GET http://localhost:3000/todoshhh/6266c0b19f2b8ac4ef49f974

###

POST http://localhost:3000/todoshhh/add-list

###

POST http://localhost:3000/todoshhh/0
Content-Type: application/json

{
  "text": "First one"
}


###

DELETE http://localhost:3000/todoshhh/6266c0ee9f2b8ac4ef49f976

###

PATCH http://localhost:3000/todoshhh/1/1
Content-Type: application/json

{
  "text": "Third one",
  "isDone": true
}
